### ISSUE TITLE
Run workspaces in kiosk mode or webapp mode

### ISSUE THREAD

**Issue by samuelcaldas** [gitpod-io/browser-extension#19]
all of these browser buttons take up unnecessary space.
Other projects that run vscode in browser like [code-server](https://github.com/cdr/code-server) have this option.

**Comment by svenefftinge** [comment]
Also, there is https://chrome.google.com/webstore/detail/gitpod-window/jhpkbhdoenpnfnnkelgpikndadikogdl

**Comment by svenefftinge** [comment]
I have pushed a new version that allows to set a "Open as popup" preference.

**Comment by samuelcaldas** [comment]
> I have pushed a new version that allows to set a "Open as popup" preference.

it just gave me a popup with running workspaces list. I'll take a look at the code tomorrow.
